### ISSUE TITLE
Getting Error While running for Data query flag

### ISSUE THREAD

**Issue by tanazza** [ligovirgo/dqsegdb#74] opened 2020-09-17 23:32 UTC
@rpfisher @duncanmmacleod 

While running the following command:

on_segment['L1'] = dq.query_str('L1','+L1:DMT-ANALYSIS_READY:1',t_0-t_unc-delay['L1'],t_0+t_on,source='dqsegdb',server="https://segments.ligo.org")

I am receiving following error: 

RuntimeError: Could not find a RFC 3820 compliant proxy credential. Please run 'grid-proxy-init -rfc' and try again.

I will appreciate any help on this issue.
Thanks,
Tanazza

**Comment by robertbruntz** [comment] 2020-10-02 14:37
Hi Tanazza -
  I think every time I've seen an "RFC 3820" issue, it's been due to X509 variables not being set properly.  Here are 2 answers that were useful in solving this problem previously:

Q: What causes errors like "RuntimeError: Could not find a RFC 3820 compliant proxy credential. Please run 'grid-proxy-init -rfc' and try again." when a user tries to run a query?

A: The program running the query probably can't find a proxy cert or if it can, it is expired or invalid. On many systems, the cert is identified by the X509_USER_PROXY variable; try 'export | grep -i x509' to see if that variable is set, and if so, what file it points to. This can probably be fixed by setting 'export X509_USER_PROXY=/etc/grid-security/[certname].pem' before running the script (or defining that variable inside the script). Note that the old method had 2 variables, X509_USER_CERT and X509_USER_KEY (a "first-class certificate and key"), and both had to be set; the proxy cert file contains both the cert and the key now, so only the first variable needs to be set (see e-mail chain between Mike Thomas and Keith Riles, 2019.04.12) - though if your system still uses 2 variables, have both of them point to the proxy cert.

A2: Here is the text from a reply that helped someone with this error: "Most scripts used to set the variables "X509_USER_KEY" and "X509_USER_CERT" to point to separate key and cert files; now, if you still use those variables, both should point to the proxy cert file, which contains both the key and the cert. Some processes just use "X509_USER_PROXY" now. I think the general procedure is to create the proxy cert file using the keytab (and then that file is good for 11.5 days), then copy the file (which is probably something like /tmp/x509up_u501) to some other location, such as /etc/grid-security/proxy-cert.pem, then set the environment variable(s) to point to that file (e.g., "export X509_USER_PROXY=/etc/grid-security/proxy-cert.pem"). Note that for a cron job, you need to set the variable(s) in the crontab file itself (i.e., add the line(s) to the file you edit with "crontab -e"), so that the variable is available to the script run by crontab. You can also try running "grid-proxy-info" from your command line, then again from the script that you're running, to help determine where the issue is (e.g., cert is available from the command line but not the script - why not? maybe echo the X509 variable value from the script as well)."

Please try the instructions above and let us know if you are still having trouble.

**Comment by robertbruntz** [comment] 2021-02-04 18:13
I contacted the user to follow up on this.  He said that the issue has been resolved.

**Closed by robertbruntz** 2021-02-04 18:13 UTC
