### ISSUE TITLE
Errors being output to stdout rather than stderr

### ISSUE THREAD

**Issue by mattpitkin** [ligovirgo/dqsegdb#14] opened 2016-06-02 21:55 UTC
If I run e.g.

<pre>
ligolw_segment_query_dqsegdb --segment-url https://segments.ligo.org --query-segments --include-segments L1:DCS-ANALYSIS_READY_C02 --gps-start-time 1126031360 --gps-end-time 1136649617 --exclude-segments L1:DCS-BAD_KAPPA_BASIC_CUT_H1_HOFT_C02:1 > L1O1segs.xml
</pre>

there are error messages output into the xml file due to them being output to `stdout`. This doesn't effect the xml if using the `-o` flag to set the output file, but it should still probably be the case that errors are sent to `stderr`.

**Comment by robertbruntz** [comment] 2021-12-06 22:27
@mattpitkin I know it's been a while, but can you confirm that this was fixed?  When I run the above command, I get a valid xml file.  On the other hand, if I run a variation with an invalid flag name (e.g., `ligolw_segment_query_dqsegdb --segment-url https://segments.ligo.org --query-segments --include-segments L1:DCS-ANALYSIS_READY_C02_bad --gps-start-time 1126031360 --gps-end-time 1136649617 --exclude-segments L1:DCS-BAD_KAPPA_BASIC_CUT_H1_HOFT_C02:1 > L1O1segs_bad.xml`), it prints an error to `stdout` and saves a similar, valid xml file, but with no useful segments in it.

**Comment by robertbruntz** [comment] 2023-02-17 05:47
Ping @mattpitkin on this.  @couvares do you have any insight into whether this is still an issue, and if so, how to reproduce it?

**Comment by couvares** [comment] 2023-02-17 16:51
@robertbruntz your comment above doesn't make sense to me.  The '>' redirects all stdout to the indicated file (and stderr to the terminal), so if that command indeed "prints an error to stdout", then it prints the error in the same stream as the xml output.  If you see the error on the terminal, then it must be printed to stderr (correctly) and not stdout.

**Comment by robertbruntz** [comment] 2023-02-17 17:07
@couvares Thanks - you're right.  I had said `stdout` when I should have said `stderr`.  I've fixed that in my comment.  I'm inclined to close this issue, since the code seems to be working correctly.  (I just wanted confirmation from @mattpitkin .)

**Comment by robertbruntz** [comment] 2023-05-24 22:16
There is no indication that this is still an issue, so the issue is being closed.  If it needs to be reopened, please so so here: https://git.ligo.org/computing/dqsegdb/client/-/issues/14 .

**Closed by robertbruntz** 2023-05-24 22:16 UTC
